<h2 style='font-family: French Script MT; font-weight: 600; font-size: 30px; text-align: left'>1.0. Import Required Libraries</h2>

In [16]:
from scipy.stats import mannwhitneyu
from itertools import combinations
import pandas as pd  
import numpy as np 

import warnings  
warnings.simplefilter("ignore")  
pd.set_option('display.max_columns', 7) 
pd.set_option('display.float_format', lambda x: '%.2f' % x)

<h2 style='font-family: French Script MT; font-weight: 600; font-size: 30px; text-align: left'>2.0. Load and Inspect Dataset</h2>

In [17]:
filepath = "Datasets/Fertilizer and Light Exposure Experiment Dataset.csv"
df = pd.read_csv(filepath)
display(df)

,Fertilizer,Light Exposure,Plant Height (cm),...,Flower Count (number),Seed Yield (g),Stomatal Conductance (mmol/m²/s)
0,Control,Full Sun,58.56,...,19.54,6.69,242.41
1,Organic,Full Shade,46.70,...,15.37,6.17,233.66
2,Control,Partial Shade,58.33,...,16.39,5.41,230.07
3,Control,Full Shade,42.73,...,12.45,4.26,154.25
4,Organic,Full Shade,41.82,...,15.14,4.64,200.54
...,...,...,...,...,...,...,...
115,Synthetic,Partial Shade,65.24,...,21.14,7.48,254.78
116,Organic,Partial Shade,63.56,...,16.11,6.17,234.22
117,Control,Partial Shade,62.75,...,17.99,6.18,278.97
118,Control,Full Shade,39.60,...,13.72,4.46,186.87
119,Synthetic,Full Shade,41.75,...,13.60,4.94,180.23

<h2 style='font-family: French Script MT; font-weight: 600; font-size: 30px; text-align: left'>3.0. Mann-Whitney U Test</h2>

In [19]:
def mannwhitneyu_test(df, group_cols, variables):
    results = []
    for category in group_cols:
        unique_groups = df[category].unique()
        group_combinations = list(combinations(unique_groups, 2))
        
        for column in variables:
            for group1, group2 in group_combinations:
                group1_data = df[df[category] == group1][column].dropna()
                group2_data = df[df[category] == group2][column].dropna()
                
                if len(group1_data) > 1 and len(group2_data) > 1:
                    t_stat, p_value = mannwhitneyu(group1_data, group2_data, alternative='two-sided')
                    
                    results.append({
                        'Group': category,
                        'Variable': column,
                        'Group 1': group1,
                        'Group 2': group2,
                        'Mean Diff.': group1_data.mean() - group2_data.mean(),
                        'U-Statistic': t_stat,
                        'P-Value': p_value,
                        'Significant (α=0.05)': 'Significant' if p_value < 0.05 else 'Not Significant'
                    })
    
    return pd.DataFrame(results)


group_cols = ['Fertilizer', 'Light Exposure']
variables = ['Plant Height (cm)', 'Leaf Area (cm²)', 'Chlorophyll Content (SPAD units)']
results = mannwhitneyu_test(df, group_cols=group_cols, variables=variables)

pd.set_option('display.float_format', '{:.4f}'.format)
display(results.style.format({
    'Mean Diff.': '{:.2f}',
    'U-Statistic': '{:.3f}',
    'P-Value': '{:.4f}'
}).background_gradient(subset=['P-Value'], cmap='YlOrRd'))

---

This analysis was performed by **Jabulente**, a passionate and dedicated data analyst with a strong commitment to using data to drive meaningful insights and solutions. For inquiries, collaborations, or further discussions, please feel free to reach out via.  

----

<div align="center">  
    
[![GitHub](https://img.shields.io/badge/GitHub-Jabulente-black?logo=github)](https://github.com/Jabulente)  [![LinkedIn](https://img.shields.io/badge/LinkedIn-Jabulente-blue?logo=linkedin)](https://linkedin.com/in/jabulente-208019349)  [![Email](https://img.shields.io/badge/Email-jabulente@hotmail.com-red?logo=gmail)](mailto:Jabulente@hotmail.com)  

</div>

<h1 style='font-size: 35px; color: red; font-family: French Script MT; font-weight: 700; text-align: center'>Data to Drive Meaningful Insights and Solutions</h1>